# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bca542b2aa5569b6ddfde3f7a6a613170ff164c4f03c95f325821e9c7ba65424faf44a1e438f58c33993f6dca2b8cf7c7a4882befe09c2118e44361ecacf953e

test:
  secret_key_base: dee96114d9c855f9f9c7deccb00ff350d83c9cb701d12682318f7308f2b8a4a5f3465fb1857fa9e140c4b470ff44eb5fb5f83a0e92e5c7c56e00d4c35f4132c9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
